language: bash
dist: bionic
before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
sudo: required

branches:
  only:
    - master
script:
  - |
  ls -d ./dockerfiles/*/ | awk -F '/' '{print $3}' | xargs -I path docker buildx build \
  --platform linux/amd64,linux/arm64 \
  ./dockerfiles/path -t "$DOCKER_ACCOUNT/csapp:path"

after_success:
  - if [ "$TO_PUSH" = "true" ]; then echo "$DOCKER_ACCOUNT_TOKEN" | docker login -u "$DOCKER_ACCOUNT" --password-stdin; else echo "WILL NOT TO PUSH IMAGES"; fi
  - if [ "$TO_PUSH" = "true" ]; then ls -d ./dockerfiles/*/ | awk -F '/' '{print $3}' | xargs -I path docker push $DOCKER_ACCOUNT/csapp:path; fi
